### ISSUE TITLE
Feature Request: Support MongoDB/Atlas

### ISSUE THREAD

**Issue by PFython** [iklobato/LightAPI#7]
Great looking module which I stumbled on from the PythonWeekly newsletter by rahul@pythonweekly.com.

Sadly not something I'd use in its current state because I'm using MongoDB/Atlas in all my client projects.  If it's a fairly easy thing to add support for this I'd be very excited to embrace it though!

All the best,
Pete

**Comment by iklobato** [comment]
Hello Pete! 
At the moment I haven't thought about any connection with nsql dbs, my priority now is to make it robust and unbreakable.
We're just getting started, and some features are still in the experimental phase. However, I'm committed to making the product as stable as possible. In the near future, it will evolve into a powerful tool for rapidly creating REST APIs.
Thanks for the feedback! You are welcome to come back here in a few months

**Comment by PFython** [comment]
Thanks for the quick reply Iklobato, and good luck with the development!
